### ISSUE TITLE
Newer Laravel versions break authentication

### ISSUE THREAD

**Issue by intensite** [davemo/end-to-end-with-angularjs#10]
There seem to be a problem with the authentication portion.

When trying to log-in, I get an error 500 from the server with this response:

```
{
   "error":{
      "type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException",
      "message":"Class User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\\Auth\\UserInterface::getRememberToken, Illuminate\\Auth\\UserInterface::setRememberToken, Illuminate\\Auth\\UserInterface::getRememberTokenName)",
      "file":"\/var\/www\/test\/end-to-end-with-angularjs\/app\/models\/User.php",
      "line":66
   }
}

```

After following the instructions on the laravel docs at: http://laravel.com/docs/upgrade#upgrade-4.1.26 

Everything works.

**Comment by ntsagkas** [comment]
Even with the added functions logout still does not work

**Comment by davemo** [comment]
@intensite @belibem thanks for the report here; if either of you have the capacity would you be willing to take a crack at updating Laravel in the repo and submitting a pull request? If not I can tackle this once I have some time :)
