### ISSUE TITLE
Including CSRF_TOKEN when using lineman

### ISSUE THREAD

**Issue by sdeering** [davemo/end-to-end-with-angularjs#12]
Hey Dave, quick question mate hope you don't mind. How would I include the CSRF Token provided by Laravel into my lineman angular app? Obviously the index page is index.us so it's not PHP and you can't simply echo the token out into the document head. I'm sure you've solved this so thought i'd ask you first. 

I probably should add that my project structure is like this:

```
project
|__front-end
|__back-end
```

Maybe it would be easier to inject the token if it was like this:

```
project
|__back-end (laravel)
|____public
|______(angular front-end files)
```

Also might be worth noting that in development, lineman serves from the generated folder. I'm working on a good solution and i'll post results in a blog post.

**Comment by davemo** [comment]
Hey @sdeering, I've used the following technique to achieve what you're talking about: 

https://gist.github.com/davemo/6141699

**Comment by davemo** [comment]
Keep in mind you will need to setup your angular app to manual bootstrap using this approach. https://docs.angularjs.org/api/ng/function/angular.bootstrap

**Comment by sdeering** [comment]
Thanks @davemo, so there isn't a way you thought of to avoid that extra HTTP request?

**Comment by davemo** [comment]
Inlining the value in a server-side template would be the only way to avoid that request @sdeering :)

**Comment by sdeering** [comment]
Just did a quick blog post on this. @davemo keen to hear what you think mate. http://angularjs4u.com/concepts/laravel-4-angularjs-architecture/

**Comment by davemo** [comment]
Nice work @sdeering! I just read your post; how you handled the CSRF_TOKEN between dev/prod makes sense, it's basically the same split of client/server assets. Injecting the meta tag for your prod build is a nice way to handle avoiding that HTTP request for the token. I'm curious though, the post didn't go into detail on how you configured bootstrapping to be manual with the requested token vs automatic with the injected token. How are you achieving that part of the setup?

**Comment by sdeering** [comment]
Thanks @davemo yeah for that bit I just checked to see if the meta tag exists. https://gist.github.com/sdeering/4356baed3692d26ab778
