### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by arivasvera** [davemo/end-to-end-with-angularjs#14]
Hello, I am following your instructions to use this project: 
1-clone this repo: git clone https://github.com/davemo/end-to-end-with-angularjs.git
2-install composer dependencies composer install
3-create a database called laravelapp
4-create your unique security key php artisan key:generate
5-run database migrations php artisan migrate
6-seed the database php artisan db:seed
7-run the app php artisan serve
8-browse to http://localhost:8000 and log in with email admin@example.org and password admin

But when I run the command "composer install", I get this error:
Mac-mini-de-Soluciones-2:end-to-end-with-angularjs simorg$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
- Installing psr/log (dev-master a78d650)
  Loading from cache
- Installing monolog/monolog (dev-master ec39618)
  Loading from cache
- Installing filp/whoops (1.0.7)
  Loading from cache
- Installing nikic/php-parser (0.9.x-dev ef70767)
  Loading from cache
- Installing jeremeamia/superclosure (1.0.1)
  Loading from cache
- Installing doctrine/lexer (dev-master 83893c5)
  Loading from cache
- Installing doctrine/annotations (dev-master 6a6bec0)
  Loading from cache
- Installing doctrine/collections (dev-master 8c5148e)
  Loading from cache
- Installing doctrine/cache (dev-master f7a1d66)
  Loading from cache
- Installing doctrine/inflector (dev-master 64de2fe)
  Loading from cache
- Installing doctrine/common (dev-master 559a805)
  Loading from cache
- Installing doctrine/dbal (2.4.x-dev f15c482)
  Loading from cache
- Installing symfony/translation (2.3.x-dev 638d6e0)
  Loading from cache
- Installing symfony/routing (2.3.x-dev 22ee195)
  Loading from cache
- Installing symfony/process (2.3.x-dev 0434822)
  Loading from cache
- Installing symfony/debug (2.3.x-dev 9760bae)
  Loading from cache
- Installing symfony/http-foundation (2.3.x-dev c8f7e5c)
  Loading from cache
- Installing symfony/event-dispatcher (2.3.x-dev 3e0b837)
  Loading from cache
- Installing symfony/http-kernel (2.3.x-dev 17bb005)
  Loading from cache
- Installing symfony/finder (2.3.x-dev fc25dab)
  Loading from cache
- Installing symfony/dom-crawler (2.3.x-dev 64b9087)
  Loading from cache
- Installing symfony/css-selector (2.3.x-dev a8826cf)
  Loading from cache
- Installing symfony/console (2.3.x-dev e593294)
  Loading from cache
- Installing symfony/browser-kit (2.3.x-dev 6a403ee)
  Loading from cache
- Installing swiftmailer/swiftmailer (v5.0.3)
  Loading from cache
- Installing predis/predis (0.8.x-dev 4123fcd)
  Loading from cache
- Installing patchwork/utf8 (v1.1.25)
  Loading from cache
- Installing nesbot/carbon (1.13.0)
  Loading from cache
- Installing ircmaxell/password-compat (1.0.x-dev 1fc1521)
  Loading from cache
- Installing symfony/filesystem (dev-master 7d97789)
  Loading from cache
- Installing classpreloader/classpreloader (1.0.2)
  Loading from cache
- Installing laravel/framework (4.0.x-dev 7be5f82)
  Loading from cache

monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/routing suggests installing symfony/config ()
symfony/routing suggests installing symfony/yaml ()
symfony/debug suggests installing symfony/class-loader ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Writing lock file
Generating autoload files
{"error":{"type":"ErrorException","message":"Undefined index: timezone","file":"\/Applications\/MAMP\/htdocs\/end-to-end-with-angularjs\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":154}}Script php artisan optimize handling the post-install-cmd event returned with an error

  [RuntimeException]  
  Error Output:       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]

Mac-mini-de-Soluciones-2:end-to-end-with-angularjs simorg$ 

May you help me?

**Comment by timothysstewart** [comment]
I'm having the same issue.

**Comment by ssi-anik** [comment]
As I can see, the app/config/app.php file is missing 
download this file and place it in app/config/ 
use composer update
should work then. 
ATTACHMENT:
https://github.com/laravel/laravel/blob/master/app/config/app.php

**Comment by iantrich** [comment]
Thanks, ssi. That did the trick!

**Comment by ssi-anik** [comment]
@iantrich, it's working perfectly now, right?

**Comment by iantrich** [comment]
My migrations didn't work last night but I think I had my database setup
incorrectly. Will look at it again tonight. Thanks.

**Comment by ssi-anik** [comment]
@iantrich Did you figure out the error?

**Comment by regenrek** [comment]
@iantrich @ssi-anik 

Not only the config/app.php is missing in the repo. You need to add the database.php file too
https://raw.githubusercontent.com/laravel/laravel/master/app/config/database.php

You can see in .gitignore file that the two files aren't included:
app/config/app.php
app/config/database.php

**Comment by lutsifer** [comment]
Both app.php and database.php attachments are missing...

**Comment by ssi-anik** [comment]
@lutsifer add those files.

**Comment by lutsifer** [comment]
@ssi-anik 
:) I really don't see any files...

**Comment by ssi-anik** [comment]
@lutsifer, 
app.php => https://github.com/laravel/laravel/blob/v4.2.11/app/config/app.php,
database.php => https://github.com/laravel/laravel/blob/v4.2.11/app/config/database.php
place those within your project_root/app/config/  folder. and name those as they are.

**Comment by lutsifer** [comment]
Thanks:)

**Comment by jakegardner** [comment]
Just in case the suggestion by @ssi-anik didn't work for anyone (i got a new error instead): create a fresh laravel 4.2 project and copy the app.php and database.php files from there to the same directory in this project.
