### ISSUE TITLE
DB Migration for the sessions table missing

### ISSUE THREAD

**Issue by IvanLim** [davemo/end-to-end-with-angularjs#2]
Hi Dave, I'm working through your second screencast now (end to end with angularjs) and it seems like the screencast has two migration scripts (one for the users table, and one for the sessions table) however the sample files provided only have the migration script for the users table.

Thanks again for the immensely helpful tutorials!

Ivan

**Comment by davemo** [comment]
Hi @IvanLim, Laravel 4 actually provides you a way to generate the sessions table automatically; I think I forgot to cover it in the screencast but it is in the list of instructions in the [README](https://github.com/davemo/end-to-end-with-angularjs/blob/master/README.md) file as Step #5:
- create the sessions migration `php artisan session:table`

Glad you are enjoying the tutorials! :)

**Comment by IvanLim** [comment]
Oh... I incorrectly assumed that the steps under App Installation were what we were going to work through in the screencast. Just ran through them and everything's fine now. Thanks! :)
