### ISSUE TITLE
Installation instructions - step 5 seems redundant (and causes an error)

### ISSUE THREAD

**Issue by mgustafsson1** [davemo/end-to-end-with-angularjs#4]
Hi Dave,

This is a minor one (and probably related to #2) - it seems like you've added a session table migration file, so if you do as suggested in step 5 in the installation instructions you'll end up with two identical migration files for the sessions table, which causes an error when you run artisan migrate.

No biggy, but might save someone a few seconds worth of debugging :)

Thanks for the great tutorial!

Regards
Mike

**Comment by davemo** [comment]
Thanks @mgustafsson1, I had more people run into problems by _not_ running the migrations step which was why I decided to add the session table migration file into the repository; but I had forgotten to remove the step that generates the migration file via artisan. This should fix that :)
