### ISSUE TITLE
update data provided by a service

### ISSUE THREAD

**Issue by mhelaiwa** [davemo/end-to-end-with-angularjs#5]
hi i have an app which has a static data "lets say users" provided by a service and 2 controllers one for view users and another to add new user.
what i'm trying to do is when the user added successfully i want to update the list of users and i am getting this error <code>$digest already in progress</code>

many thanks in advance :)

here is my code

<pre>
var app = angular.module('usersApp',[]);
app.factory("myusers", function() {
    return {
        set : function(users){users_arr = users;},
        get : function(){return users_arr;}
    };
});

app.factory('form',function($http,myusers){
    return {
        save : function(scope,url){
            var response = $http.post(url, scope.user);
            response.success(function(res){
                myusers.set(res.users);
                scope.$apply(); // here i get the error :)
            });
        }
    }
});

app.controller('ViewController',function($scope,myusers){
    $scope.myusers = myusers.get();
});

app.controller('AddController',function($scope,$http,form){
    $scope.save = function(){
        form.save($scope,'/account/users');
    }
});
</pre>

**Comment by mhelaiwa** [comment]
I'v changed the code to this and it worked perfectly. but i do not know if this is the right way this is my first day playing with Angularjs :)
thanks again

<pre>
var app = angular.module('usersApp',[]);
app.factory("myusers", function() {
    return return users_arr; // the array comes from the DB and binded to a js var in the DOM using laravel
});
app.factory('form',function($http,$rootScope){
    return {
        save : function(scope,url){
            var response = $http.post(url, scope.user);
            response.success(function(res){
                // users comes within the response of adding functionality to reload the grid
                $rootScope.myusers.set(res.users); 
            });
        }
    }
});
app.controller('ViewController',function($rootScope,myusers){
    $rootScope.myusers = myusers.get();
});
app.controller('AddController',function($scope,$http,form){
    $scope.save = function(){
        form.save($scope,'/account/users');
    }
});
</pre>

**Comment by davemo** [comment]
Hi @enghelewa, the problem with your initial code was that you were doing `$scope.$apply()` within your $http.success callback; angular will implicitly schedule an update to the $digest within any of its core services, like $http, so you don't need to do that.
