### ISSUE TITLE
html5Mode doesnt seem to work

### ISSUE THREAD

**Issue by whoisandy** [davemo/end-to-end-with-angularjs#6]
Tried to inject the locationProvider in the run block & an App::missing method so that any 404 fallsback to the index or home route. But the flash doesnt seem to work nor the sessions. How do we get this running ? Am I missing something out here ? Do we have to do something with the .htaccess file which comes with laravel ?

**Comment by davemo** [comment]
Hi @whoisandie, you can only inject Providers within the `.config` block, so if you want to configure html5Mode you'll need to do it there.

As for setting up apache to support pushState, here's some good reading: http://www.josscrowcroft.com/2012/code/htaccess-for-html5-history-pushstate-url-routing/
