### ISSUE TITLE
Passing the Credentials static

### ISSUE THREAD

**Issue by nofear87** [davemo/end-to-end-with-angularjs#8]
Is there a secure way to passing the credentials to the api as constant?

I try 

$http.defaults.headers.common['Authorization'] = 'Basic username:password';

and i try to send them with the resource header, But this doenst work, too.

**Comment by davemo** [comment]
Hi @nofear87, the only "secure" way would be to make sure you're using SSL (https) for your application in production. As for where you put the credentials, in a header or a cookie would be most appropriate.
